import '../../core/protocol/telemetry.dart';

/// A plausible mid-corner telemetry frame: theme previews in the settings,
/// widget tests and screenshots.
const sampleTelemetry = Telemetry(
  speed: 41.7,
  rpm: 6900,
  maxRpm: 7800,
  gear: '4',
  gearIndex: 4,
  maxGearIndex: 6,
  fuel: 0.62,
  fuelVolume: 31.4,
  waterTemp: 92,
  oilTemp: 104,
  envTemp: 21,
  boost: 2.4,
  engineRunning: true,
  ignitionLevel: 2,
  lowBeam: true,
  highBeam: false,
  signalLeft: true,
  parkingBrake: false,
  hasAbs: true,
  absActive: false,
  hasEsc: true,
  escActive: true,
  hasTcs: true,
  tcsActive: false,
  odometer: 48213000,
  shiftLight: false,
  driveMode: 'Sport',
  tirePressures: {'FL': 210, 'FR': 212, 'RL': 205, 'RR': 95},
  tirePressuresNominal: {'FL': 220, 'FR': 220, 'RL': 210, 'RR': 210},
  radar: [
    RadarTarget(x: -3.5, y: 6, heading: 0),
    RadarTarget(x: 3.4, y: -12, heading: 180, length: 5.2),
    RadarTarget(x: 0.5, y: 18, heading: 10, length: 12, width: 2.5),
  ],
  bodyDamage: {'FL': 0.35, 'ML': 0.08},
  engineDamage: ['radiatorLeak'],
  tyres: {
    'FL': TyreState(temp: 92, working: 85, condition: 96),
    'FR': TyreState(temp: 84, working: 85, condition: 97),
    'RL': TyreState(temp: 62, working: 85, condition: 98),
    'RR': TyreState(temp: 118, working: 85, condition: 91),
  },
  brakeTemps: {'FL': 420, 'FR': 405, 'RL': 210, 'RR': 640},
  hotBrakes: ['RR'],
  clutchTemp: 95,
  shafts: ['driveshaft', 'wheelaxleRL', 'wheelaxleRR'],
  brokenParts: ['wheelaxleRL'],
  engineAt: 0.18,
  receivedFields: {'speed', 'rpm'},
);
