version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: monthly
    commit-message:
      prefix: build
    open-pull-requests-limit: 5
