/// 5-digit pairing code generated by the game (`core_remoteController`).
///
/// Accepted inputs, because the QR content already changed once:
///   - BeamNG >= 0.39 QR: `https://play.google.com/...remotecontrol#54688`
///   - older QR: `<text>#<code>`
///   - a code typed by hand.
class PairingCode {
  final String securityCode;

  const PairingCode(this.securityCode);

  static final RegExp _validCode = RegExp(r'^\d{4,6}$');
  static final RegExp _digits = RegExp(r'\d{4,6}');

  /// 1. text after the last `#`; 2. otherwise the first run of 4-6 digits.
  static PairingCode? tryParse(String raw) {
    final trimmed = raw.trim();
    if (trimmed.isEmpty) return null;

    String? candidate;
    final hashIndex = trimmed.lastIndexOf('#');
    if (hashIndex >= 0 && hashIndex < trimmed.length - 1) {
      candidate = trimmed.substring(hashIndex + 1).trim();
    }
    if (candidate == null || !_validCode.hasMatch(candidate)) {
      candidate = _digits.firstMatch(trimmed)?.group(0);
    }
    if (candidate == null || !_validCode.hasMatch(candidate)) return null;
    return PairingCode(candidate);
  }
}
